# build
markdown: kramdown
permalink: /blog/:year/:title/
exclude:
  - CNAME
  - Gemfile
  - LICENSE
  - Rakefile
  - README.md
  - vendor/
  - vnu/
  - vnu.zip
layouts_dir: ./_noita
sass:
  sass_dir: noita/_scss
  style: compressed
# compress layout in _noita/compress.html
compress_html:
  clippings: all
  endings: all
  comments: ["<!--", "-->"]
  ignore:
    envs: [travis]
# theme
noita:
  name: it.gerull.nl
  title: ITnerary
  description: A static blog where I keep my cheatsheet, recipes and information about procedures and tips. In short, my route through Information Technology.
  author:
    name: Claus Gerull
    url: http://www.gerull.nl/
  lang: en
  favicons:
    - /assets/2014/04/21/favicon-152.png
  topbar:
    toggle: Menu
    right:
      - name: About
        url: /about/
      # - name: Guide
      #   url: /guide/
      - name: Blog
        url: /blog/
    #  button - name: Repository
    #     url: https://github.com/penibelst/jekyll-noita
    #     class: small 
